//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by JobSeek.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_JOBSEEK_DIALOG              102
#define IDD_JOBINFO_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     129
#define IDD_REGISTER_DIALOG             129
#define IDD_DIALOG2                     130
#define IDD_SEARCH_DIALOG               130
#define IDD_DIALOG3                     131
#define IDD_LOGIN_DIALOG                131
#define IDD_DIALOG4                     132
#define IDD_SEARCHRESULT_DIALOG         132
#define IDB_BITMAP_BGL                  136
#define IDB_BITMAP_BGR                  139
#define IDB_BITMAP_BGIN                 140
#define IDB_BITMAP_BGS                  141
#define IDC_EDIT2                       1001
#define IDC_EDIT3                       1002
#define IDC_INDUSTRY_EDIT               1002
#define IDC_EDIT4                       1003
#define IDC_PROPERTY_EDIT               1003
#define IDC_EDIT5                       1004
#define IDC_EDIT6                       1005
#define IDC_ReleaseDate_EDIT            1005
#define IDC_EDIT7                       1006
#define IDC_WORKDURATION_EDIT           1006
#define IDC_EDIT8                       1007
#define IDC_PROVINCE_EDIT               1007
#define IDC_WORKPLACE_EDIT              1007
#define IDC_EDIT9                       1008
#define IDC_EDUCATION_EDIT              1008
#define IDC_EDIT10                      1009
#define IDC_HIRENUMBER_EDIT             1009
#define IDC_LIST1                       1010
#define IDC_WORKRESPONSIBILITY_LIST     1010
#define IDC_CONTACTOR_EDIT              1010
#define IDC_EDIT11                      1011
#define IDC_RADIO1                      1011
#define IDC_MALE_RADIO                  1011
#define IDC_WORKADDRESS_EDIT            1011
#define IDC_CONTACTNUMBER_EDIT          1011
#define IDC_RADIO2                      1012
#define IDC_EDIT24                      1012
#define IDC_FEMALE_RADIO                1012
#define IDC_CONTACTEMAIL_EDIT           1012
#define IDC_EDIT12                      1014
#define IDC_COMPEMAIL_EDIT              1014
#define IDC_EDIT13                      1015
#define IDC_JOBNAME_EDIT                1015
#define IDC_EDIT14                      1016
#define IDC_REPASSWORD_EDIT             1016
#define IDC_EDIT15                      1017
#define IDC_EMAIL_EDIT                  1017
#define IDC_EMAILAddress_EDIT           1017
#define IDC_EMAILCode_EDIT              1018
#define IDC_COMBO2                      1019
#define IDC_EDUCATION_COMBO             1019
#define IDC_COMBO_REGION                1019
#define IDC_EMAILSMTP_EDIT              1020
#define IDC_EDIT1                       1021
#define IDC_MAJOR_EDIT                  1021
#define IDC_EDIT16                      1022
#define IDC_EMAILPORT_EDIT              1022
#define IDC_EDIT17                      1023
#define IDC_EMAILContent_EDIT           1023
#define IDC_COMBO6                      1024
#define IDC_EDIT20                      1024
#define IDC_EXPCLOC_COMBO               1024
#define IDC_PROVINCE_COMBO              1024
#define IDC_EDIT21                      1025
#define IDC_REGION_COMBO                1025
#define IDC_COMBO7                      1026
#define IDC_EDIT22                      1026
#define IDC_EXPCIND_COMBO               1026
#define IDC_EMAILAttachment_EDIT        1026
#define IDC_EDIT18                      1027
#define IDC_EDIT23                      1027
#define IDC_REGION_EDIT                 1027
#define IDC_EMAILName_EDIT              1027
#define IDC_EDIT19                      1028
#define IDC_COMBO3                      1029
#define IDC_EDIT25                      1029
#define IDC_MAJOR_COMBO                 1029
#define IDC_EDIT26                      1030
#define IDC_COMBO4                      1031
#define IDC_BUTTON1                     1032
#define IDC_JOB_GO                      1032
#define IDC_CHECK_USERNAME              1032
#define IDC_CLOSE                       1032
#define IDC_PRERECORD                   1032
#define IDC_BUTTON2                     1033
#define IDC_BUTTON_UPDATA               1033
#define IDC_NEXTRECORD                  1033
#define IDC_BUTTON3                     1034
#define IDC_SENDMAIL                    1034
#define IDC_BUTTON4                     1035
#define IDC_BUTTON5                     1036
#define IDC_CHECK1                      1037
#define IDC_CHECKCAREER                 1037
#define IDC_CHECK2                      1038
#define ID_REGISTER                     1038
#define IDC_CHECKCOMPANY                1038
#define IDC_CHECK3                      1039
#define ID_LOGIN                        1039
#define IDC_CHECK4                      1040
#define IDC_USERNAME_LABLE              1040
#define IDC_CHECK5                      1041
#define IDC_PASSWORD_LABLE              1041
#define IDC_USERNAME_EDIT               1042
#define IDC_PASSWORD_EDIT               1043
#define IDC_REPASSWORD_LABEL            1046
#define IDC_SEX_LABEL                   1050
#define IDC_AGE_LABLE                   1051
#define IDC_AGE_EDIT                    1052
#define IDC_MAJOR_LABEL                 1054
#define IDC_EXPERENCE_LABEL             1055
#define IDC_EXPERENCE_EDIT              1056
#define IDC_EXPCLOC_LABEL               1057
#define IDC_EXPCIND_LABEL               1058
#define IDC_EXPCSAL_LABEL               1059
#define IDC_EXPCSAL_EDIT                1060
#define ID_REGISTER_OK                  1061
#define ID_REGISTER_CANCEL              1062
#define ID_REGISTER_CLOSE               1062
#define IDC_JOB_EDIT                    1065
#define IDC_COMPANYNAME_EDIT            1067
#define IDC_WORKPLACE_LABEL             1068
#define IDC_SALARY_LABEL                1070
#define IDC_SALARY_EDIT                 1071
#define ID_SEARCH_OK                    1072
#define ID_SEARCH_JOB                   1072
#define ID_SEARCH_CANCEL                1073
#define ID_INPORT_DATA                  1073
#define IDC_JOBNAME_COMBO               1074
#define IDC_COMPANYNAME_COMBO           1075
#define IDC_SELRESUME_LABEL             1076
#define ID_SENDRESUME_OK                1077
#define ID_SENDRESUME_CANCEL            1078
#define IDC_SELRESUME_COMBO             1079
#define IDC_INDUSTRY_LABEL              1079
#define IDC_POPULATION_LABEL            1080
#define IDC_PROPERTY_LABEL              1081
#define IDC_RELEASEDATE_LABEL           1082
#define IDC_COMPANYNAME_LABEL           1083
#define IDC_JOBNAME_LABEL               1084
#define IDC_USERNAME_LABEL              1085
#define IDC_PASSWORD_LABEL              1086
#define IDC_EMAIL_LABEL                 1087
#define IDC_WORKDURATION_LABEL          1088
#define IDC_EMAILCode_LABEL             1088
#define IDC_EDUCATION_LABEL             1089
#define IDC_HIRENUMBER_LABEL            1090
#define IDC_EMAIL_SmtpServer            1090
#define IDC_EMAILSmtp_LABEL             1090
#define IDC_CONTACTOR_LABEL             1091
#define IDC_EMAILPort__LABEL            1091
#define IDC_CONTACTNUMBER_LABEL         1092
#define IDC_EMAILContent_LABEL          1092
#define IDC_CONTACTEMAIL_LABEL          1093
#define IDC_EMAIL_Attachment_LABEL      1093
#define IDC_WORKADDRESS_LABEL           1094
#define IDC_EMAILName_LABEL             1094
#define IDC_COMPEMAIL_LABEL             1095
#define IDC_USERNAME_STATIC             1096
#define IDC_EMAIL_STATIC                1097
#define IDC_COMBO_PROVINCE              1098
#define IDC_email                       1099
#define IDC_EMAILAddress_LABEL          1100

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1103
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
